version: '3.8'

services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production

  frontend:
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - backend
